send_command:
  description: Send device command through RFPlayer.
  fields:
    command:
      name: Command
      description: The command to be sent. [add Protocol]
      required: true
      default: " " 
      example: "HELLO"
      selector:
        select:
          options:
              - " "
              - 1 FACTORYRESET. FORMAT JSON. STATUS. JAMMING 7. JAMMING SIMULATE
              - HELLO
              - PING
              - "ON"
              - "OFF"
              - ALL_ON
              - ALL_OFF
              - DIM %4
              - EDISIOFRAME
              - ASSOC
              - DISSOC
              - ASSOC_OFF
              - DISSOC_OFF
              - RECEIVER + *
              - REPEATER + *
              - REPEATER ON
              - REPEATER OFF
              - LEDACTIVITY 0
              - LEDACTIVITY 1
              - JAMMING 7
              - JAMMING SIMULATE
              - FREQ L 433920
              - FREQ L 433420
              - FREQ L 0
              - FREQ H 868950
              - FREQ H 868350
              - FREQ H 0
              - SELECTIVITY L 4
              - SELECTIVITY H 4
              - SENSITIVITY L 4
              - SENSITIVITY H 4
              - DSPTRIGGER L 6
              - DSPTRIGGER H 8
              - RFLINK 0
              - RFLINK 1
              - RFLINKTRIGGER L 12
              - RFLINKTRIGGER H 10
              - LBT 16
              - FORMAT RFLINK OFF
              - FORMAT RFLINK BINARY
              - " "
          mode: dropdown
    protocol:
      name: Protocol
      description: RFPlayer compatible protocol.[Parametre]
      required: true
      example: CHACON
      selector:
        select:
          options:
              - " "
              - "BLYSS"
              - "CHACON"
              - "DOMIA"
              - "EDISIO"
              - "EDISIOFRAME"
              - "FS20"
              - "JAMMING"
              - "JAMMING SIMULATE"
              - "KD101"
              - "OREGON"
              - "OREGONV1"
              - "OREGONV2"
              - "OREGONV3/OWL"
              - "OWL"
              - "PARROT"
              - "RTS"
              - "TIC"
              - "VISONIC"
              - "VISONIC433"
              - "VISONIC868"
              - "X10"
              - "X2D"
              - "X2D433"
              - "X2D868"
              - "X2DELEC"
              - "X2DGAS"
              - "X2DSHUTTER"
              - " "
          mode: dropdown
    device_address:
      name: Device address
      description: Device address.
      required: false
      example: A1
      selector:
        text:
    device_id:
      name: Device ID
      description: Device ID.
      required: false
      example: 40
      selector:
        text:
    automatic_add:
      name: Create entity
      description: Create associated switch entity
      required: true
      default: false
      selector:
        boolean:
    entity_type:
      name: Entity type
      description: Type of entity created
      required: false
      default: switch
      selector:
        select:
          options:
              - "cover"
              - "number"
              - "sensor"
              - "switch"
          mode: dropdown

set_device_address:
  description: Set device adress for RFPlayer entity.
  fields:
    device_address:
      name: Device address
      description: Device address.
      required: false
      example: A1
      selector:
        text:

set_device_platform:
  description: Set device platform for RFPlayer entity.
  fields:
    entity_type:
      name: Entity type
      description: Type of entity created
      required: false
      default: switch
      selector:
        select:
          options:
              - "cover"
              - "number"
              - "sensor"
              - "switch"
          mode: dropdown

test_frame:
  description: Test a frame inside RFPlayer.
  fields:
    frame:
      name: Frame
      description: The frame to test.
      required: true
      example: 'ZIA33{ "frame" :{"header": {"frameType": "0", "cluster": "0", "dataFlag": "0", "rfLevel": "-91", "floorNoise": "-107", "rfQuality": "4", "protocol": "5", "protocolMeaning": "OREGON", "infoType": "4", "frequency": "433920"},"infos": {"subType": "0", "id_PHY": "0x1A2D", "id_PHYMeaning": "THGR122/228/238/268,THGN122/123/132", "adr_channel": "22274",  "adr": "87",  "channel": "2",  "qualifier": "33",  "lowBatt": "1", "measures" : [{"type" : "temperature", "value" : "+21.3", "unit" : "Celsius"}, {"type" : "hygrometry", "value" : "58", "unit" : "%"}]}}}'
      selector:
        text:
